ERT_summary:
  version: 0.3
  table_summary:
  - name: diannao.DRAM
    actions:
    - name: read
      energy: 1
    - name: write
      energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.DRAM
      estimator: dummy_table
  - name: diannao.OutputBuffer
    actions:
    - name: read
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: write
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.OutputBuffer
      estimator: dummy_table
  - name: diannao.InputBuffer
    actions:
    - name: read
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: write
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.InputBuffer
      estimator: dummy_table
  - name: diannao.PsumRegFile
    actions:
    - name: read
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: write
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.PsumRegFile
      estimator: dummy_table
  - name: diannao.WeightBuffer
    actions:
    - name: read
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: write
      average_energy: 1.0
      max_energy: 1
      min_energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.WeightBuffer
      estimator: dummy_table
  - name: diannao.MACs
    actions:
    - name: mac_random
      energy: 1
    - name: mac_reused
      energy: 1
    - name: mac_gated
      energy: 1
    - name: idle
      energy: 0
    primitive_estimation(s):
    - name: diannao.MACs
      estimator: dummy_table
