ERT:
  version: 0.3
  tables:
  - name: diannao.DRAM
    actions:
    - name: read
      arguments: null
      energy: 1
    - name: write
      arguments: null
      energy: 1
    - name: idle
      arguments: null
      energy: 0
  - name: diannao.OutputBuffer
    actions:
    - name: read
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: idle
      arguments: null
      energy: 0
  - name: diannao.InputBuffer
    actions:
    - name: read
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: idle
      arguments: null
      energy: 0
  - name: diannao.PsumRegFile
    actions:
    - name: read
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: idle
      arguments: null
      energy: 0
  - name: diannao.WeightBuffer
    actions:
    - name: read
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: read
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 0
        data_delta: 1
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 0
      energy: 1
    - name: write
      arguments:
        address_delta: 1
        data_delta: 1
      energy: 1
    - name: idle
      arguments: null
      energy: 0
  - name: diannao.MACs
    actions:
    - name: mac_random
      arguments: null
      energy: 1
    - name: mac_reused
      arguments: null
      energy: 1
    - name: mac_gated
      arguments: null
      energy: 1
    - name: idle
      arguments: null
      energy: 0
