ART_summary:
  version: 0.3
  table_summary:
  - name: diannao.DRAM
    area: 1
    primitive_estimations: dummy_table
  - name: diannao.OutputBuffer
    area: 1
    primitive_estimations: dummy_table
  - name: diannao.InputBuffer
    area: 1
    primitive_estimations: dummy_table
  - name: diannao.PsumRegFile
    area: 1
    primitive_estimations: dummy_table
  - name: diannao.WeightBuffer
    area: 1
    primitive_estimations: dummy_table
  - name: diannao.MACs
    area: 1
    primitive_estimations: dummy_table
