architecture:
  version: 0.3
  local:
  - name: diannao.DRAM
    class: DRAM
    attributes:
      instances: 1
      technology: 40nm
      type: LPDDR4
      width: 64
      word-bits: 16
  - name: diannao.OutputBuffer
    class: SRAM
    attributes:
      block-size: 16
      depth: 512
      entries: 1024
      instances: 1
      latency: 5ns
      meshX: 1
      n_banks: 1
      n_rd_ports: 0
      n_rdwr_ports: 1
      n_wr_ports: 0
      read_bandwidth: 16
      technology: 40nm
      width: 64
      word-bits: 16
      write_bandwidth: 16
  - name: diannao.InputBuffer
    class: SRAM
    attributes:
      block-size: 16
      depth: 512
      entries: 1024
      instances: 1
      latency: 5ns
      meshX: 1
      n_banks: 1
      n_rd_ports: 0
      n_rdwr_ports: 1
      n_wr_ports: 0
      read_bandwidth: 16
      technology: 40nm
      width: 64
      word-bits: 16
      write_bandwidth: 16
  - name: diannao.PsumRegFile
    class: regfile
    attributes:
      cluster-size: 16
      depth: 1
      entries: 1
      instances: 16
      latency: 5ns
      meshX: 16
      n_ports: 2
      read_bandwidth: 1
      technology: 40nm
      width: 16
      word-bits: 16
      write_bandwidth: 1
  - name: diannao.WeightBuffer
    class: regfile
    attributes:
      cluster-size: 256
      depth: 1
      entries: 64
      instances: 256
      latency: 5ns
      meshX: 16
      n_ports: 2
      read_bandwidth: 1
      technology: 40nm
      width: 16
      word-bits: 16
      write_bandwidth: 1
  - name: diannao.MACs
    class: intmac
    attributes:
      datawidth: 16
      instances: 256
      latency: 5ns
      meshX: 16
      num_pipeline_stages: 2
      technology: 40nm
      word-bits: 16
