ART:
  version: 0.3
  tables:
  - name: diannao.DRAM
    area: 1
  - name: diannao.OutputBuffer
    area: 1
  - name: diannao.InputBuffer
    area: 1
  - name: diannao.PsumRegFile
    area: 1
  - name: diannao.WeightBuffer
    area: 1
  - name: diannao.MACs
    area: 1
